(() => {
'use strict';
const $ = id => document.getElementById(id);
const page = document.body.dataset.page;
const cmp = new Intl.Collator('be');
const labels = {poem:'верш',translation:'пераклад',news:'навіны',culture:'культура',language:'мова',idea:'ідэя'};
const params = new URLSearchParams(location.search);
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function link(href,cls,text){const a=el('a',cls,text);a.href=href;return a;}
function authorUrl(id){return 'author.html?id='+encodeURIComponent(id);}
function postUrl(id){return 'post.html?id='+encodeURIComponent(id);}
function validId(id){return typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);}
function httpUrl(value){if(!value)return null;try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}}
function initials(name){return (name||'').trim().split(/\s+/).filter(Boolean).map(s=>s[0]).slice(0,2).join('');}
function photo(author,cls){const fallback=el('div',cls+(cls==='profile-photo'?' profile-placeholder':''),initials(author.name));const url=httpUrl(author.avatar_path);if(!url)return fallback;const img=el('img',cls);img.src=url;img.alt=author.name;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>img.replaceWith(fallback);return img;}
function date(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('be',{dateStyle:'medium'}).format(d);}
function errorBox(target,e){console.error('пра.бел:',{code:e?.code,message:e?.message,details:e?.details,hint:e?.hint});target.replaceChildren(el('p','error','не ўдалося загрузіць дадзеныя. абнаві старонку або паспрабуй пазней.'));}
const config=window.PRA_CONFIG;
let db;
try{if(!window.supabase||!config)throw new Error('не загружана бібліятэка або config.js');db=window.supabase.createClient(config.url,config.publishableKey);}catch(e){errorBox($('detail')||$('grid'),e);return;}
const authorCols='id,name,bio,avatar_path,quote,instagram_url,tiktok_url,telegram_url';
const postCols='id,author_id,title,body,category,published_at,created_at,original_author,original_language';
async function all(makeQuery){const rows=[];for(let from=0;;from+=500){const {data,error}=await makeQuery().range(from,from+499);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<500)return rows;}}
function postCard(p,author,i){const c=el('article','card'),top=el('div','card-top');top.append(el('span','',String(i+1).padStart(2,'0')),el('span','',labels[p.category]||'матэрыял'));const h=el('h3');h.append(link(postUrl(p.id),'',p.title));const text=p.body||'';c.append(top,h,el('div','preview',p.category==='poem'||p.category==='translation'?text.split('\n').slice(0,4).join('\n'):text.slice(0,180)+(text.length>180?'…':'')));const by=el('p','byline');if(author)by.append(link(authorUrl(author.id),'',author.name));else by.textContent='аўтар недаступны';c.append(by,link(postUrl(p.id),'read','чытаць цалкам ↗'));return c;}
function authorCard(a,count,i){const c=el('article','card');c.append(el('div','card-top',String(i+1).padStart(2,'0')),photo(a,'avatar-mini'));const h=el('h3');h.append(link(authorUrl(a.id),'',a.name));c.append(h,el('div','preview',a.bio||a.quote||'пазнаёмся з аўтарам праз яго творы.'),el('p','byline','апублікаваных матэрыялаў: '+count),link(authorUrl(a.id),'read','пра аўтара ↗'));return c;}
async function listing(){const [authors,posts]=await Promise.all([all(()=>db.from('authors').select(authorCols).order('id')),all(()=>db.from('posts').select(postCols).eq('status','published').order('id'))]);const byId=new Map(authors.map(a=>[a.id,a]));authors.slice().sort((a,b)=>cmp.compare(a.name,b.name)).forEach(a=>$('filter').add(new Option(a.name,a.id)));const selected=params.get('author_id')||params.get('author');if(selected){const a=authors.find(a=>a.id===selected||a.name===selected);if(a)$('filter').value=a.id;}
function render(){const q=$('search').value.trim().toLocaleLowerCase('be'),grid=$('grid');grid.replaceChildren();if(page==='authors'){const rows=authors.filter(a=>a.name.toLocaleLowerCase('be').includes(q)).sort((a,b)=>cmp.compare(a.name,b.name));$('count').textContent='аўтараў: '+rows.length;rows.forEach((a,i)=>grid.append(authorCard(a,posts.filter(p=>p.author_id===a.id).length,i)));}else{const rows=posts.filter(p=>(page!=='poems'||p.category==='poem')&&(page!=='translations'||p.category==='translation')&&(page!=='culture'||!['poem','translation'].includes(p.category))&&(!$('filter').value||p.author_id===$('filter').value)&&(!$('category').value||p.category===$('category').value)&&(p.title+' '+(byId.get(p.author_id)?.name||'')+' '+(p.body||'')).toLocaleLowerCase('be').includes(q));rows.sort((a,b)=>$('sort').value==='title'?cmp.compare(a.title,b.title):$('sort').value==='author'?cmp.compare(byId.get(a.author_id)?.name||'',byId.get(b.author_id)?.name||'')||cmp.compare(a.title,b.title):(Date.parse(b.published_at||b.created_at)||0)-(Date.parse(a.published_at||a.created_at)||0));$('count').textContent='матэрыялаў: '+rows.length;rows.forEach((p,i)=>grid.append(postCard(p,byId.get(p.author_id),i)));}if(!grid.children.length)grid.append(el('p','empty','нічога не знойдзена.'));}
['search','filter','sort','category'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));render();}
async function authorPage(){const target=$('detail'),id=params.get('id');if(!validId(id)){target.replaceChildren(el('p','empty','некарэктная спасылка на аўтара.'));return;}const {data:a,error}=await db.from('authors').select(authorCols).eq('id',id).maybeSingle();if(error)throw error;if(!a){target.replaceChildren(el('p','empty','аўтар не знойдзены.'));return;}document.title=a.name+' / пра.бел';target.replaceChildren(link('authors.html','back','← пра_аўтараў'));const profile=el('section','profile'),left=el('div'),right=el('div');left.append(photo(a,'profile-photo'));const socials=el('div','socials');[['instagram',a.instagram_url,['instagram.com']],['tiktok',a.tiktok_url,['tiktok.com']],['telegram',a.telegram_url,['t.me','telegram.me']]].forEach(([label,value,hosts])=>{const safe=httpUrl(value);if(!safe)return;const host=new URL(safe).hostname;if(!hosts.some(h=>host===h||host.endsWith('.'+h)))return;const s=link(safe,'',label+' ↗');s.target='_blank';s.rel='noopener noreferrer';socials.append(s);});left.append(socials);right.append(el('div','kicker','пра аўтара'),el('h1','',a.name));if(a.bio)right.append(el('div','bio',a.bio));if(a.quote)right.append(el('blockquote','quote',a.quote));if(!a.bio&&!a.quote)right.append(el('p','small','інфармацыя пра аўтара хутка з’явіцца.'));profile.append(left,right);target.append(profile);
const posts=await all(()=>db.from('posts').select(postCols).eq('author_id',id).eq('status','published').in('category',['poem','translation']).order('id'));posts.sort((a,b)=>(Date.parse(b.published_at||b.created_at)||0)-(Date.parse(a.published_at||a.created_at)||0));for(const [type,label] of [['poem','вершы'],['translation','пераклады']]){const section=el('section'),head=el('div','chapter'),rows=posts.filter(p=>p.category===type);head.append(el('h2','',label),el('span','small',String(rows.length)));section.append(head);const grid=el('div','grid');rows.forEach((p,i)=>grid.append(postCard(p,a,i)));if(!rows.length)grid.append(el('p','empty','пакуль няма апублікаваных твораў.'));section.append(grid);target.append(section);}}
async function postPage(){const target=$('detail'),id=params.get('id');if(!validId(id)){target.replaceChildren(el('p','empty','некарэктная спасылка на твор.'));return;}const {data:p,error}=await db.from('posts').select(postCols).eq('id',id).eq('status','published').maybeSingle();if(error)throw error;if(!p){target.replaceChildren(el('p','empty','твор не знойдзены або яшчэ не апублікаваны.'));return;}const {data:a,error:ae}=await db.from('authors').select('id,name').eq('id',p.author_id).maybeSingle();if(ae)throw ae;document.title=p.title+' / пра.бел';const literary=['poem','translation'].includes(p.category);const back=p.category==='poem'?'poems.html':p.category==='translation'?'translations.html':'culture.html';target.replaceChildren(link(back,'back','← '+(p.category==='poem'?'вершы':p.category==='translation'?'пераклады':'пра_культуру')));const article=el('article','work');article.append(el('div','kicker',labels[p.category]||'матэрыял'),el('h1','',p.title));const meta=el('div','work-meta');if(a)meta.append(link(authorUrl(a.id),'',(p.category==='translation'?'пераклад: ':'')+a.name));meta.append(el('span','',date(p.published_at||p.created_at)));article.append(meta);if(p.category==='translation'&&(p.original_author||p.original_language)){article.append(el('p','original',[p.original_author?'аўтар арыгіналу: '+p.original_author:'',p.original_language?'мова арыгіналу: '+p.original_language:''].filter(Boolean).join(' · ')));}article.append(el('div','work-body'+(literary?'':' prose'),p.body||''));target.append(article);if(literary)await comments(article,p.id);}
async function comments(container,postId){const section=el('section','comments'),head=el('h2','','каментарыі'),list=el('div');list.setAttribute('aria-live','polite');section.append(head,list);container.append(section);const form=el('form','comment-form');const nameLabel=el('label','','як цябе называць'),name=el('input');name.name='display_name';name.required=true;name.maxLength=60;name.autocomplete='nickname';nameLabel.append(name);const bodyLabel=el('label','','твой каментарый'),body=el('textarea');body.name='body';body.required=true;body.maxLength=2000;bodyLabel.append(body);const trap=el('input');trap.name='website';trap.tabIndex=-1;trap.autocomplete='off';trap.hidden=true;const button=el('button','btn','адправіць на мадэрацыю');button.type='submit';const status=el('p','status');status.setAttribute('role','status');form.append(nameLabel,bodyLabel,trap,el('p','form-note','без рэгістрацыі. імя не правяраецца. каментарый з’явіцца пасля мадэрацыі.'),button,status);section.append(form);
form.addEventListener('submit',async e=>{e.preventDefault();if(trap.value)return;const display_name=name.value.trim(),text=body.value.trim();if(!display_name||!text){status.textContent='запоўні імя і каментарый.';return;}button.disabled=true;status.textContent='адпраўляем…';try{const {error}=await db.from('comments').insert({post_id:postId,display_name,body:text});if(error)throw error;form.reset();status.textContent='дзякуй! каментарый адпраўлены на мадэрацыю.';}catch(e){console.error('каментарый:',e);status.textContent='не ўдалося адправіць каментарый. паспрабуй пазней.';}finally{button.disabled=false;}});
try{const rows=await all(()=>db.from('comments').select('id,display_name,body,created_at').eq('post_id',postId).eq('status','published').order('created_at').order('id'));head.textContent='каментарыі · '+rows.length;if(!rows.length)list.append(el('p','small','пакуль няма апублікаваных каментарыяў.'));rows.forEach(c=>{const item=el('article','comment'),h=el('div','comment-head');h.append(el('span','',c.display_name),el('time','',date(c.created_at)));item.append(h,el('p','',c.body));list.append(item);});}catch(e){console.error('каментарыі:',e);list.append(el('p','small','не ўдалося загрузіць каментарыі.'));}}
const active=page==='author'?'authors':page==='post'?null:page;document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===active){a.classList.add('active');a.setAttribute('aria-current','page');}});
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||e.defaultPrevented||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||a.target||a.hasAttribute('download')||reduced||('startViewTransition' in document))return;const u=new URL(a.href,location.href);if(u.origin!==location.origin||!u.pathname.endsWith('.html')||(u.pathname===location.pathname&&u.search===location.search))return;e.preventDefault();document.body.classList.add('leaving');setTimeout(()=>location.assign(u.href),180);});window.addEventListener('pageshow',()=>document.body.classList.remove('leaving'));
(async()=>{try{if(page==='author')await authorPage();else if(page==='post')await postPage();else await listing();}catch(e){errorBox($('detail')||$('grid'),e);}})();
})();
